version: "2"

services:
  dengue-api:
    container_name: dengue-api
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    environment:
      - GEOCODE_API_KEY=${GEOCODE_API_KEY}
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:4.0
    container_name: dengue-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
